### ISSUE TITLE
Red screen then freeze every time it is done and i exit

### ISSUE THREAD

**Issue by KillerTre** [nedwill/fasthax#50] opened 2017-01-08 03:25 UTC
Red screen why

**Comment by nneto** [comment] 2017-01-08 08:00
https://github.com/nedwill/fasthax/issues/46

**Comment by trilleplay** [comment] 2017-01-08 10:54
Duplicate Of Error #46 
Reccomend you closing this error thead @KillerTre .

[RESOLVED]

**Comment by nedwill** [comment] 2017-01-09 02:47
This should be fixed in beta 4.

**Closed as completed by nedwill** 2017-01-09 02:47 UTC
